- name : variables
  hosts: localhost
  vars: #variables declared
    Course: "Terraform"
    Trainer: "Siva"
    Duration: "30days"
  tasks:
  - name: print override info
    vars: #task level declaration
      Course: "Devops"
    ansible.builtin.debug:
      msg: "I am learning {{Course}} from {{Trainer}} with {Duration}"

  - name: print info
    ansible.builtin.debug:
      msg:  "I am learning {{Course}} from {{Trainer}} with {Duration}"