- name: vars datatypes
  hosts: localhost
  vars:
    Course: Devops with AWS
    Tools:
    - Ansible
    - Shell
    Experience:
      AWS: 2
      Terraform: 3
      Docker: 3
    Realtime: true
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hello I am learning {{Course}}, with tools {{Tools}} and Experience of  
      {{Experience}},and Realproject {{Realtime}}"
