- name : filter conditions
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: no
  tasks:
  - name: check the number lessthan
    ansible.builtin.debug:
      msg: "The given number {{number}} is lessthan 10"
    when: number | int < 20
  - name: check the number greaterthan
    ansible.builtin.debug:
      msg: "The given number {{number}} is greater than 10"
    when: number | int >=10
