- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{WISHES | default('welcome') }}"
      #msg: "Hello {{course | default('Ansible') }}"
- name: convert to uppercase
  hosts: localhost
  vars:
      message: "Hello good morning"
  tasks:
  - name: convert lower to upper
    ansible.builtin.debug:
      msg: "Convert the message to upper {{message | upper}}"