- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{WISHES | default('welcome') }}"
      #msg: "Hello {{course | default('Ansible') }}"