- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{WISHES | default('welcome') }}"
      #msg: "Hello {{course | default('Ansible') }}"
- name: convert to uppercase
  hosts: localhost
  vars:
      message: "Hello good morning"
  tasks:
  - name: convert lower to upper
    ansible.builtin.debug:
      msg: "Convert the message to upper {{message | upper}}"
- name: convert to lower
  hosts: localhost
  vars:
    greetings: " WELCOME TO OUR TEAM"
  tasks:
  - name: coverting to lower
    ansible.builtin.debug:
      msg: "Hello {{greetings | lower}}"
- name: distinct values
  hosts: localhost
  vars:
    Duplicates: {1,1,2,2,3,3,4,4,5,5}
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "After removing duplicates {{Duplicates | unique}}"
- name: dictionary to list
  hosts: localhost
  vars:
    Dictionary:
      course: Ansible
      Duration: 7days
      Trainer: Venkat
  tasks:
  - name: convert from dictionary to list
    ansible.builtin.debug:
     msg: " Before convert {{Dictionary}}"
     msg: " After convert {{Dictionary | dict2items}}"
  - name: convert items to disctionary
    vars:
      items:
        - {'key': 'course', 'value': 'Ansible'}
        - {'key': 'Duration', 'value': '7days'}
        - {'key': 'Trainer', 'value': 'Venkat'}
    tasks:
    - name: Beforconverting to dictionary
      ansible.builtin.debug:
        msg: " converting the items {{items | items2dict}}"
  
